export const GLOBALTYPES = {
    AUTH: "AUTH",
    ALERT: "ALERT",
    THEME: "THEME",
    GET_INFOR_USER:'GET_INFOR_USER',
    GET_USER_ID : 'GET_USER_ID',
    GET_FOLLOW : 'GET_FOLLOW',
    AVATAR_BY_USER: "AVATAR_BY_USER",
    STATUS: 'STATUS',
    REPLY : 'REPLY',
    FOLLOWING : 'FOLLOWING'
}